### PR TITLE
Added Config to the mod

### LINKED ISSUE #1: [Suggestion] Add a config file to adjust the compass position
Hi, I maintain a modpack called [LethalExpansions](https://thunderstore.io/c/lethal-company/p/goodCompany/LethalExpansions_Modpack/) and one of the mods are [LCBetterClock](https://thunderstore.io/c/lethal-company/p/BlueAmulet/LCBetterClock/), unfortunately, after the v1.2.0 update the BetterClock HUD is overlaid by the compass.

It would be nice for this mod to have a config feature that allows to change the compass's position to be lowered like in the previous version. Currently, the only workaround is to lower the clock which would not be ideal because it blocks visibility a lot.

image

### PR DESCRIPTION
**Pull request by Entity378**
I implemented in a very simple way the possibility to change the X and Y position of the compass. 
I haven't tested it but it should work fine.

UPDATE: I've tested that it works as it should

### CODE REVIEW

**Comment by iwotastic** [comment]
Thank you for your PR! I do have a few comments though before I approve...

- Even though the current default position conflicts with clock mods like LCBetterClock, it does work as a good default for vanilla Lethal Company, so I would prefer to leave the default Y position as-is. (instead of -235)
- Going along with the last bullet point, I would make it configurable whether the clock's position is adjusted, so that users who prefer/use the default clock can have an optimal experience as well. (i.e. A boolean configuration item `ShouldMoveClockDown` with default value `true`)
  - This is also an item that I would be willing to discuss or help with, especially given that I have considered splitting this out into a sort of "HUD Tools" mod API that myself and others can use.

I also have two minor coding style/administrative comments:

- A minor coding style nitpick, but I would make sure to keep using camel case for the config names. (i.e. `CompassPosX` instead of `CompassXpos`)
- Since I may want to make more changes before releasing v1.3.0, please revert the changes made to `manifest.json`, `README.md`, and `IwotasticsCompassMod.csproj`.

Thanks again for your PR and I am happy to explain or help with any of these things!

**Comment by Entity378** [comment]
> Thank you for your PR! I do have a few comments though before I approve...
> 
> * Even though the current default position conflicts with clock mods like LCBetterClock, it does work as a good default for vanilla Lethal Company, so I would prefer to leave the default Y position as-is. (instead of -235)
> * Going along with the last bullet point, I would make it configurable whether the clock's position is adjusted, so that users who prefer/use the default clock can have an optimal experience as well. (i.e. A boolean configuration item `ShouldMoveClockDown` with default value `true`)
>   
>   * This is also an item that I would be willing to discuss or help with, especially given that I have considered splitting this out into a sort of "HUD Tools" mod API that myself and others can use.
> 
> I also have two minor coding style/administrative comments:
> 
> * A minor coding style nitpick, but I would make sure to keep using camel case for the config names. (i.e. `CompassPosX` instead of `CompassXpos`)
> * Since I may want to make more changes before releasing v1.3.0, please revert the changes made to `manifest.json`, `README.md`, and `IwotasticsCompassMod.csproj`.
> 
> Thanks again for your PR and I am happy to explain or help with any of these things!

Ok, I'll fix it now

**Comment by Entity378** [comment]
> Thank you for your PR! I do have a few comments though before I approve...
> 
> * Even though the current default position conflicts with clock mods like LCBetterClock, it does work as a good default for vanilla Lethal Company, so I would prefer to leave the default Y position as-is. (instead of -235)
> * Going along with the last bullet point, I would make it configurable whether the clock's position is adjusted, so that users who prefer/use the default clock can have an optimal experience as well. (i.e. A boolean configuration item `ShouldMoveClockDown` with default value `true`)
>   
>   * This is also an item that I would be willing to discuss or help with, especially given that I have considered splitting this out into a sort of "HUD Tools" mod API that myself and others can use.
> 
> I also have two minor coding style/administrative comments:
> 
> * A minor coding style nitpick, but I would make sure to keep using camel case for the config names. (i.e. `CompassPosX` instead of `CompassXpos`)
> * Since I may want to make more changes before releasing v1.3.0, please revert the changes made to `manifest.json`, `README.md`, and `IwotasticsCompassMod.csproj`.
> 
> Thanks again for your PR and I am happy to explain or help with any of these things!

I implemented your suggestions, is it ok now?

**Comment by iwotastic** [comment]
Hi, thank you! Much better, but I would like you to completely revert the version bump (to 1.2.0, not doing a minor version bump) and the changelog (I'll bump this when I feel the time is right because I may include more changes before dropping v1.3.0, and I'll credit you in the changelog).

I also feel like the automatic disabling of clock movement when the compass position is changed may seem not seem intuitive to users, it also prevents users from potentially wanting to slightly tweak the distance between the clock and the compass (because doing so would cause the clock to revert position and then potentially overlap the text).

**Comment by Entity378** [comment]
> Hi, thank you! Much better, but I would like you to completely revert the version bump (to 1.2.0, not doing a minor version bump) and the changelog (I'll bump this when I feel the time is right because I may include more changes before dropping v1.3.0, and I'll credit you in the changelog).
> 
> I also feel like the automatic disabling of clock movement when the compass position is changed may seem not seem intuitive to users, it also prevents users from potentially wanting to slightly tweak the distance between the clock and the compass (because doing so would cause the clock to revert position and then potentially overlap the text).

So the check should be done just to see if the `ShouldMoveClockDown` config is set to `true` or `false` right?

**Comment by iwotastic** [comment]
Yup! Exactly, no additional checks.

**Comment by Entity378** [comment]
> Yup! Exactly, no additional checks.

Done

**Comment by iwotastic** [comment]
Excellent! I will now merge your changes!

**Comment by Entity378** [comment]
> Excellent! I will now merge your changes!

Ok, THX

**Pull request merged**
